---
- name: Prepare
  hosts: all
  gather_facts: true
  vars:
    pip_install_packages:
      - docker
      - docker-compose
  tasks:
    # to get ansible_default_ipv4 var
    - name: install required packages
      package:
        name: "{{ item.name }}"
        state: present
      with_items:
        - name: iproute2
        - name: iptables

  roles:
    - geerlingguy.docker
    - geerlingguy.pip
