---
jobs:
  include:
    - &test
      stage: test
      language: python
      python: "2.7"
      cache: pip
      services:
        - docker
      install:
        - pip install ansible
        - pip install docker-py
        - pip install molecule
      script:
        - molecule test
    - <<: *test
      script:
        - molecule test --scenario-name non-docker
    - <<: *test
      script:
        - molecule test --scenario-name non-docker-custom
    - <<: *test
      script:
        - molecule test --scenario-name non-docker-bauth

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
