---
- name: Install iptables-persistent
  package:
    name: iptables-persistent
    state: present

- name: Close upstream ports
  iptables:
    action: insert
    chain: DOCKER-USER
    protocol: tcp
    in_interface: "{{ ansible_default_ipv4.interface }}"
    destination_port: "{{ item.port }}"
    jump: DROP
  notify: persist iptables
  with_items: "{{ dp__upstream }}"

- name: Get container IP for metal proxies
  command: "docker inspect nginx-{{ upstream.svc_name }} -f '{% raw %}{{{% endraw %}.NetworkSettings.Networks.{{ dp__network_name }}.IPAddress{% raw %}}}{% endraw %}'"
  register: metal_proxies_ips
  when: not upstream.is_container
  with_items: "{{ dp__upstream }}"
  loop_control:
    loop_var: upstream
    label: upstream.svc_name
  changed_when: false

- name: debug
  debug:
    msg: "{{ metal_proxies_ips }}"

- name: Open path from metal proxies to local servers
  iptables:
    action: insert
    chain: INPUT
    protocol: tcp
    in_interface: docker0
    source: "{{ item.stdout }}"
    destination_port: "{{ item.upstream.port }}"
    jump: ACCEPT
  notify: persist iptables
  with_items: "{{ metal_proxies_ips.results }}"
  when: not item.upstream.is_container
