---
- name: Install necessary packages
  package:
    name: "{{ item.name }}"
    state: present
  with_items:
    - name: ufw

- name: Close upstream ports
  ufw:
    rule: deny
    port: "{{ item.port }}"
  with_items: "{{ dp__upstream_ports }}"

- name: Open http port
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Open https port
  ufw:
    rule: allow
    port: 443
    proto: tcp
  when: dp__https_enable

- name: Create nginx-proxy docker network
  docker_network:
    name: nginx-proxy

