---
- name: Load variables for HTTP
  include_vars:
    file: http.yml
  when: not dp__le_enable

- name: Load variables for HTTPS
  include_vars:
    file: https.yml
  when: dp__le_enable

- name: Install iptables-persistent
  package:
    name: iptables-persistent
    state: present

- name: Close upstream ports
  iptables:
    action: insert
    chain: DOCKER-USER
    protocol: tcp
    in_interface: "{{ ansible_default_ipv4.interface }}"
    destination_port: "{{ item.port }}"
    jump: DROP
  notify: persist iptables
  with_items: "{{ dp__upstream }}"

- name: Create the upstream network
  docker_network:
    name: "{{ dp__network_name }}"

- name: Add upstream apps to network
  template:
    src: templates/docker-compose.proxy.yml.j2
    dest: "{{ item.project_src }}/docker-compose.proxy.yml"
    mode: '0400'
    owner: root
    group: root
  with_items: "{{ dp__upstream }}"

- name: Create SSL certificates volume
  docker_volume:
    name: ssl_certs
  when: dp__le_enable

- name: Start proxy service
  docker_container:
    image: jwilder/nginx-proxy
    name: nginx-proxy
    env:
      ENABLE_IPV6: "{{ dp__ipv6_enable }}"
    volumes: "{{ _dp__np_volumes }}"
    ports: "{{ _dp__np_ports }}"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy:
    restart_policy: always
    networks:
      - name: "{{ dp__network_name }}"
    state: started

- name: Start letsencrypt companion
  docker_container:
    image: jrcs/letsencrypt-nginx-proxy-companion
    name: nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ssl_certs:/etc/nginx/certs
    volumes_from:
      - nginx-proxy
  when: dp__le_enable

- name: Wait for LE companion to generate DH parameters (takes a long time, several minutes)
  wait_for:
    timeout: 300
  when: dp__le_enable

- name: Recreate upstream services with extended config
  docker_service:
    project_src: "{{ item.project_src }}"
    services: "{{ item.svc_name }}"
    files:
      - "{{ item.doco | default('docker-compose.yml')}}"
      - docker-compose.proxy.yml
    # attach to new upstreams network
    recreate: always
  with_items: "{{ dp__upstream }}"
