---
- name: Converge
  hosts: all
  become: true
  vars:
    dp__testing: true
    dp__le_enable: false
    dp__upstream:
      - port: 5000
        svc_name: webapp
        project_src: /opt/webapp
        vhost: test.example.org
  roles:
    - role: ansible-role-docker-proxy
