---
- name: Converge
  hosts: all
  become: true
  vars:
    dp__le_enable: true
    dp__le_email: test@example.org
    dp__le_test: true
    dp__upstream:
      - port: 5000
        svc_name: webapp
        project_src: /opt/webapp
        vhost: test.example.org
        is_container: true
  roles:
    - role: ansible-role-docker-proxy
