---
- name: Converge
  hosts: all
  gather_facts: false
  become: true
  vars:
    dp__testing: true
    dp__le_test: true
    dp__le_email: test@example.org
    dp__upstream:
      - port: 5000
        svc_name: webapp
        project_src:
  pre_tasks:
    # to get ansible_default_ipv4 var
    - name: install required package for facts
      package:
        name: iproute2
        state: present

    - name: gather facts
      setup:

  roles:
    - role: ansible-role-docker-proxy
