---
- name: Prepare
  hosts: all
  gather_facts: true
  vars:
    pip_install_packages:
      - docker
      - docker-compose
  tasks:
    - name: Create dummy webapp dir
      file:
        path: /opt/webapp
        state: directory

    - name: Copy docker-compose
      copy:
        src: files/docker-compose.yml
        dest: /opt/webapp/docker-compose.yml

    - name: start dummy webapp
      docker_service:
        project_src: /opt/webapp
        state: present

    # to get ansible_default_ipv4 var
    - name: install required packages
      package:
        name: "{{ item.name }}"
        state: present
      with_items:
        - name: iproute2
        - name: iptables

  roles:
    - geerlingguy.docker
    - geerlingguy.pip
