---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install pip
      package:
        name: python-pip
        state: present

    - name: Install pip deps
      pip:
        name: "{{ item.name }}"
        state: present
      with_items:
        - name: docker
        - name: docker-compose

    - name: Create fake webapp dir
      file:
        path: /opt/webapp
        state: directory
